In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("House Price India.csv")
df

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
0,6762810145,42491,5,2.50,3650,9050,2.0,0,4,5,...,1921,0,122003,52.8645,-114.557,2880,5400,2,58,2380000
1,6762810635,42491,4,2.50,2920,4000,1.5,0,0,5,...,1909,0,122004,52.8878,-114.470,2470,4000,2,51,1400000
2,6762810998,42491,5,2.75,2910,9480,1.5,0,0,3,...,1939,0,122004,52.8852,-114.468,2940,6600,1,53,1200000
3,6762812605,42491,4,2.50,3310,42998,2.0,0,0,3,...,2001,0,122005,52.9532,-114.321,3350,42847,3,76,838000
4,6762812919,42491,3,2.00,2710,4500,1.5,0,0,4,...,1929,0,122006,52.9047,-114.485,2060,4500,1,51,805000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14615,6762830250,42734,2,1.50,1556,20000,1.0,0,0,4,...,1957,0,122066,52.6191,-114.472,2250,17286,3,76,221700
14616,6762830339,42734,3,2.00,1680,7000,1.5,0,0,4,...,1968,0,122072,52.5075,-114.393,1540,7480,3,59,219200
14617,6762830618,42734,2,1.00,1070,6120,1.0,0,0,3,...,1962,0,122056,52.7289,-114.507,1130,6120,2,64,209000
14618,6762830709,42734,4,1.00,1030,6621,1.0,0,0,4,...,1955,0,122042,52.7157,-114.411,1420,6631,3,54,205000
14619,6762831463,42734,3,1.00,900,4770,1.0,0,0,3,...,1969,2009,122018,52.5338,-114.552,900,3480,2,55,146000

In [6]:
'''Q1. What is the average, median, and standard deviation of house prices?
'''
df["Price"].agg(["mean","median","std"])

mean      538932.218331
median    450000.000000
std       367532.380804
Name: Price, dtype: float64

In [7]:
'''
Q2. Which number of bedrooms is most common?
'''
df["number of bedrooms"].mode()

0    3
Name: number of bedrooms, dtype: int64

In [8]:
df["number of bedrooms"].value_counts()

number of bedrooms
3     6612
4     4724
2     1844
5     1079
6      176
1      136
7       30
8       11
9        3
10       3
33       1
11       1
Name: count, dtype: int64

In [9]:
'''. Q3 Check if the price data is skewed
'''
df["Price"].skew()

np.float64(4.269297720707116)

 Q3 The price data is positively skewed (right-skewed), indicating that some houses have very high prices compared to the majority of houses.

In [13]:
'''Q4. What is the average price for each number of bedrooms?
'''
df.head()
df.groupby("number of bedrooms")["Price"].mean()

number of bedrooms
1     3.089638e+05
2     3.985476e+05
3     4.632776e+05
4     6.361988e+05
5     7.752550e+05
6     8.375815e+05
7     1.016544e+06
8     1.208455e+06
9     7.766663e+05
10    8.200000e+05
11    5.200000e+05
33    6.400000e+05
Name: Price, dtype: float64

In [16]:
'''Q5.  What is the relationship between living area and price? (Use : Area without Basement).
'''
df["Area of the house(excluding basement)"].corr(df["Price"])
#The correlation between living area (excluding basement) and price is 0.615, indicating a positive relationship. As the living area increases, the house price generally tends to increase.

np.float64(0.6152204198678108)

In [19]:
'''Q6. Identify any anomalies where houses have high prices but low areas.
'''
df["Area of the house(excluding basement)"].median()
df["Price"].median()
df[(df["Area of the house(excluding basement)"] < df["Area of the house(excluding basement)"].median()) &
   (df["Price"] > df["Price"].median())]

,id,Date,number of bedrooms,number of bathrooms,living area,lot area,number of floors,waterfront present,number of views,condition of the house,...,Built Year,Renovation Year,Postal Code,Lattitude,Longitude,living_area_renov,lot_area_renov,Number of schools nearby,Distance from the airport,Price
7,6762813599,42491,3,1.75,2240,10578,2.0,0,0,5,...,1923,0,122006,52.9254,-114.482,1570,10578,3,71,750000
8,6762813600,42491,3,2.50,2390,6550,1.0,0,2,4,...,1955,0,122009,52.8014,-114.598,2010,6550,1,73,750000
9,6762814461,42491,4,2.25,2200,11250,1.5,0,0,5,...,1920,0,122010,52.9145,-114.391,2320,10814,2,53,698000
12,6762815461,42491,4,2.00,1520,6200,1.5,0,0,3,...,1945,0,122006,52.9080,-114.459,1910,6200,3,80,640000
14,6762815737,42491,3,2.25,1750,1572,2.5,0,0,3,...,2005,0,122013,52.8798,-114.511,2410,3050,3,51,626000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14578,6762812266,42734,3,1.00,1160,10732,1.0,0,0,3,...,1953,0,122048,52.8691,-114.395,2390,13656,1,62,875000
14589,6762816343,42734,3,1.75,1410,4080,1.0,0,0,4,...,1950,0,122007,52.9108,-114.574,1410,4080,3,60,600000
14593,6762817230,42734,5,2.25,2130,4360,1.0,0,2,3,...,1959,0,122032,52.8886,-114.585,1830,5000,1,79,565000
14594,6762818680,42734,4,1.75,1780,8768,1.0,0,0,4,...,1951,0,122022,52.9385,-114.473,1590,8100,1,64,518000
14595,6762818937,42734,4,2.00,1630,1724,1.5,0,0,3,...,1915,1970,122003,52.8772,-114.552,1780,3810,1,79,509000

In [20]:
'''Q7. Compare average price based on number of floors and houses with or without waterfront
'''
df.groupby("number of floors")["Price"].mean()

number of floors
1.0    4.369769e+05
1.5    5.549301e+05
2.0    6.487372e+05
2.5    1.106233e+06
3.0    5.663281e+05
3.5    1.205875e+06
Name: Price, dtype: float64

In [21]:
df.groupby("waterfront present")["Price"].mean()

waterfront present
0    5.304174e+05
1    1.641902e+06
Name: Price, dtype: float64

In [24]:
'''Q8. Identify the minimum and maximum house price. What does this indicate?
'''
df["Price"].min()
df["Price"].max()
#The minimum and maximum house prices show that house prices vary over a wide range, indicating considerable variation in house prices.

7700000

In [25]:
'''9. Which location (zipcode/area) has the highest average price?


'''
df.groupby("Postal Code")["Price"].mean()

Postal Code
122003    8.503290e+05
122004    8.398533e+05
122005    6.389622e+05
122006    6.136386e+05
122007    5.728347e+05
              ...
122068    3.153815e+05
122069    4.812247e+05
122070    2.799618e+05
122071    2.348311e+06
122072    2.342158e+05
Name: Price, Length: 70, dtype: float64

0. Write at least 5 insights from your analysis.
ans--
Price data is positively skewed, with skewness of 4.2, indicating that some houses have much higher prices than most houses.
Living area and price have a positive relationship, with a correlation of 0.615. This means larger living areas generally tend to have higher prices.
House prices vary over a wide range, as shown by the difference between the minimum and maximum prices.
Average house price varies by number of bedrooms, showing that bedroom count is associated with differences in average price.
Houses with low area but relatively high prices were identified as possible anomalies using the median-based filter.